[package]
name = "libsofa-sys"
version = "0.1.0"
authors = ["Andrea Riciputi <andrea.riciputi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
